StudentsAndTheirCats/StudentsAndTheirCats/urls.py
from django.contrib import admin
from django.urls import path, include
from catsandstudents import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('catsandstudents', include('catsandstudents.urls')),
]

StudentsAndTheirCats/catsandstudents/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from catsandstudents import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'catsandstudents'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

StudentsAndTheirCats/catsandstudents/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    number_of_cats = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'students'

    def __str__(self):
        return f"{self.first_name}{self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.number_of_cats = self.cat_set.count()
        super().save(*args, **kwargs)


class Cat(models.Model):
    name_of_cat = models.CharField(max_length=32)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'cats'

    def __str__(self):
        return f"{self.name_of_cat}"

StudentsAndTheirCats/catsandstudents/views.py
from django.shortcuts import render
from catsandstudents.models import Cat, Student


def index(request):
    context_dict = {}
    context_dict = {'students': Student.objects.order_by('last_name')}
    return render(request, 'catsandstudents/index.html', context=context_dict)


def about(request):
    context_dict = {}
    context_dict = {'cats': Cat.objects.order_by('name_of_cat')}
    return render(request, 'catsandstudents/about.html', context=context_dict)

StudentsAndTheirCats/templates/catsandstudents/about.html
<!DOCTYPE html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

<html>
<style>
    body {
        background: gray;
        color: white;
        font-family: Bahnschrift, serif;
    }
</style>
    <body>
        <img src="{% static "images/cats_with_fire.jpg" %}" alt="Picture of the Cat">
        <div class="MainText">
            <h1 class="Heading">
                All the cats are:
            </h1>
            {% if cats %}
                <ul class="ListText">
                    {% for cat in cats %}
                        <li>{{ cat.name_of_cat }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong> This student has no cats. </strong>
            {% endif %} <br />
        </div>
     <div class="FooterText">
    <footer>
        <a class="linkText" href="/">Back to Home Page</a>
    </footer>
</div>
    </body>
</html>

StudentsAndTheirCats/templates/catsandstudents/index.html
<!DOCTYPE html>
{% load static %}

<html>
<style>
    body {
        background: gray;
        color: white;
        font-family: Bahnschrift, serif;
    }
</style>
<head>
    <title>Students & their Cats!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <script>
        function imageSwap() {
            let ele = document.getElementById('image');
            if (ele) {
                if (ele.src.includes("cat.png")) {
                    ele.src = "{% static 'images/cat.jpg' %}";
                } else {
                    ele.src = "{% static 'images/cat.png' %}";
                }
            }
        }
    </script>
</head>
<body>
    <img class="image"
         id="image"
         src="{% static "images/cat.png" %}"
         alt="Picture of Cat">
    <button class="btn" onclick="imageSwap()">Another Cat!</button>
    <div class="mainText">
        <h1>The Students and their Cats:</h1>
        {% if students %}
            <ul class="listText">
                {% for student in students %}
                    <li>
                        {{ student.first_name }} {{ student.last_name }} has <strong>{{ student.cat_set.all.count }}</strong> cat{% if student.cat_set.all.count != 1 %}s{% endif %}
                        <ul>
                            {% for cat in student.cat_set.all|dictsort:'name_of_cat' %}
                                <li>{{ cat.name_of_cat }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h2 class="Heading"> No students present.</h2>
        {% endif %}
    </div>
    <div class="FooterText">
        <footer>
            <a class="linkText" href="{% url 'catsandstudents:about' %}">More about the Pets of the Students</a>
        </footer>
    </div>
</body>
</html>